#╔═══╗╔╗   ╔═══╗╔═══╗╔═══╗╔═══╗╔═══╗╔══╗ ╔═══╗╔═══╗╔═══╗╔═══╗╔═══╗
#╚╗╔╗║║║   ║╔══╝║╔═╗║╚╗╔╗║║╔══╝║╔═╗║║╔╗║ ║╔═╗║║╔═╗║║╔═╗║╚╗╔╗║║╔═╗║
#║║║║║║   ║╚══╗║║ ║║ ║║║║║╚══╗║╚═╝║║╚╝╚╗║║ ║║║║ ║║║╚═╝║ ║║║║║╚══╗
#║║║║║║ ╔╗║╔══╝║╚═╝║ ║║║║║╔══╝║╔╗╔╝║╔═╗║║║ ║║║╚═╝║║╔╗╔╝ ║║║║╚══╗║
#╔╝╚╝║║╚═╝║║╚══╗║╔═╗║╔╝╚╝║║╚══╗║║║╚╗║╚═╝║║╚═╝║║╔═╗║║║║╚╗╔╝╚╝║║╚═╝║
#╚═══╝╚═══╝╚═══╝╚╝ ╚╝╚═══╝╚═══╝╚╝╚═╝╚═══╝╚═══╝╚╝ ╚╝╚╝╚═╝╚═══╝╚═══╝
#=================================================================
# Discord Leaderboards Plugin Configuration
# https://dsc.gg/sundevs | KASUN#8771
#=================================================================
# STORAGE SETTINGS (H2) (MYSQL)
#=================================================================
# Available Options
# Local Databases - H2 (Default)
# Remote Databases - MYSQL
storage-method: 'h2'

# Remote Database Settings
# you don't have to change anything if you are using H2
address: 'localhost'
database: 'minecraft'
username: 'root'
password: ''

#=================================================================
# Leaderboards
#=================================================================
# you have to list leaderboard name (filename) here for load them
# you can disable the leaderboard by removing them from this list
# all leaderboard configs must be inside the leaderboards folder
# and must follow default template as example leaderboard
leaderboards:
  - 'example'


#=================================================================
# Default Settings
#=================================================================
# You can change these values for each leaderboard in their own
# config file witch you can find inside leaderboards folder
webhook-url: '-'  #Required !!!
webhook-avatar-url: '-'
webhook-user-name: 'DLeaderBoards'

embed-title: 'Leaderboard' #Required !!!
embed-url: '-'
embed-colour: '#00ffee'
embed-footer: '-'
embed-image: '-'
embed-thumbnail: '-'

#=================================================================
# Debug Settings
#=================================================================
# Reserved for Plugin Developer, Do not Change Anything Here
# It May Break Your Plugin
pluginversion: 0.0.1
firsttime: true


